<div class="titulo">Escopo</div>

<!-- ABRIMENTO DA TAP DO PHP -->
<?php

/**
 * INICIALIZANDO UMA FUÇÃO 
 * PARA INICIAR VC COMEÇA DIZENDO QUE VAI SER UMA FUNÇÃO DEPOIS PASSA O N0ME DELE E COLOCA OS PARENTESES PARA CASO FOR PASSAR ALGUM PARAMETRO
 */
function exemplo(){
    echo "Olá";
}

//NESSA FUNÇÃO SIMPLISMENTE ELA É DO TIPO VOID, POIS ELA NÃO VAI VE RETORNAR NADA, SO VAI EXIBIR ALGUMA INFORMAÇÃO

//CHAMANDO A FUNÇÃO APRA ELA SER EXECUTADA
exemplo();

/**
 * INICIANDO UMA FUNÇÃO COM UM RETORNO
 */

function exemplo2(){
    return "Retorno bem sucedido";
}
//MESMO EU CHAMANDO A FUNÇÃO ELA NÃO EXIBIR NADA NA TELA, POIS ELA SO ESTA RETORNANDO UMA RESPOSTA, POREM NÃO ESTA IMPRIMINDO NADA.
exemplo2();

//PARA IMPRIMIR OQUE RETORNOU DA FUNÇÃO, TEM QUE COLOCAR A TAG 'echo' DO PHP PARA EXIBIR A INFORMAÇÃO RETORNADA DA FUNÇÃO.

echo "<br>" . exemplo2();

?>